name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'
      
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./website
        run: npm install

      - name: Build
        working-directory: ./website
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com